# @package _global_

sfm_dir: 'data/datasets/sfm_output_hmerge/outputs_softmax_loftr_loftr'


names:
    # Train Set
    - '0410'
    - '0413'
    - '0414'
    - '0415'
    - '0416'
    - '0418'
    - '0420'
    - '0421'
    - '0443'
    - '0445'
    - '0448'
    - '0460'
    - '0461'
    - '0462'
    - '0463'
    - '0464'
    - '0465'
    - '0477'
    - '0479'
    - '0484'
    - '0499'
    - '0506'
    - '0507'
    - '0509'
    - '0512'
    - '0513'
    - '0516'
    - '0529'
    - '0530'
    - '0531'
    - '0532'
    - '0533'
    - '0536'
    - '0542'
    - '0545'
    - '0546'
    - '0549'
    - '0556'
    - '0561'
    - '0562'
    - '0563'
    - '0566'
    - '0567'
    - '0569'
    - '0571'
    - '0572'
    - '0573'
    - '0574'
    - '0575'
    # # Val set
    # - "0601"
    # - "0602"
    # - "0603"
    # - "0604"
    # - "0605"
    # - "0606"
    # - "0607"
    # - "0608"
    # - "0609"
    # - "0610"
    # - "0611"
    # - "0612"
    # - "0613"
    # - "0614"
    # - "0615"
    # - "0616"
    # - "0617"
    # - "0618"
    # - "0619"
    # - "0620"
    # - "0621"
    # # Test set
    # # - '0408'
    # # - '0409'
    # # - '0419'
    # # - '0422'
    # # - '0423'
    # # - '0424'
    # # - '0447'
    # # - '0450'
    # # - '0452'
    # # - '0455'
    # # - '0456'
    # # - '0458'
    # # - '0459'
    # # - '0466'
    # # - '0468'
    # # - '0469'
    # # - '0470'
    # # - '0471'
    # # - '0472'
    # # - '0473'
    # # - '0474'
    # # - '0476'
    # # - '0480'
    # # - '0483'
    # # - '0486'
    # # - '0487'
    # # - '0488'
    # # - '0489'
    # # - '0490'
    # # - '0492'
    # # - '0493'
    # # - '0494'
    # # - '0495'
    # # - '0496'
    # # - '0497'
    # # - '0498'
    # # - '0500'
    # # - '0501'
    # # - '0502'
    # # Test set of OnePose_LowTexture
    # - '0700'
    # - '0701'
    # - '0702'
    # - '0703'
    # - '0706'
    # - '0707'
    # - '0708'
    # - '0710'
    # - '0712'
    # - '0713'
    # - '0714'
    # - '0715'
    # - '0718'
    # - '0719'
    # - '0720'
    # - '0721'
    # - '0722'
    # - '0723'
    # - '0724'
    # - '0725'
    # - '0726'
    # - '0727'
    # - '0728'
    # - '0729'
    # - '0730'
    # - '0731'
    # - '0732'
    # - '0733'
    # - '0734'
    # - '0735'
    # - '0736'
    # - '0737'
    # - '0740'
    # - '0741'
    # - '0742'
    # - '0743'
    # - '0744'
    # - '0745'
    # - '0746'
    # - '0748'


hydra:
    run:
        dir: ${work_dir}